### Site Settings ###
title               : Elouan Grimm
description         : >-
                      I mess around with tech 💻,
                      tidy up Chrome with Tidy Tab Groups 🗂️,
                      and snap photos with my crappy phone 📱.
baseurl             : ""             # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
open_new_tab        : true           # Opens external URLs in new tab (works for posts, projects and navbar only)

description-seo     : Hi, I'm Elouan Grimm, a 13-year-old tech enthusiast with a passion for game development, photography, and coding. I’ve had the opportunity to contribute to Epimetheus Games, assisting in the creation of their first two indie games, EyeSore and Project Prometheus. You can check out these innovative games on itch.io.
                      In addition to my work in game development, I am an active contributor to the Tidy Tab Groups project, created by @MoeBazziGIT. I play an important role in enhancing the user experience, and you can join the community on Discord to collaborate and engage with fellow developers!
                      Based in Cape Town, I am bilingual, fluent in French and English, which allows me to collaborate with a diverse community of tech enthusiasts worldwide. When I’m not coding or developing games, I’m behind the camera, capturing moments with my phone, which I share on Instagram through my photography posts.
                      Explore my projects, games, and more on my personal site. Whether you’re into tech, indie games, or photography, you’ll find something exciting here.

### Navbar Settings ###
nav_exclude:                         # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/blog.html                  # This is temporary, to disable the blog.
  - pages/minimalnewtab.md           # This is temporary, to disable this page.
  - pages/comments.md
  - pages/playlist.md

### Author Info ###
author:
  name              : Elouan Grimm
  image             : https://raw.githubusercontent.com/elouangrimm/elouangrimm/274f03ea2876291a47db6ab07b66f9c6f66019e2/profile.png
  email             : hello@elouan.xyz
  github            : elouangrimm
  instagram         : elouangrimm
  spotify-stats     : elouangrimm
  bluesky           : elouan.xyz
  whatsapp          : 19712661720
  reddit            : elouangrimm

### Posts ###
permalink: /posts/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - vendor
  - Gemfile
  - Gemfile.lock